/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luisnavarrete
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    String seleccion="";
    int puntosExamen=0;
    int puntostotal=0;
    int a=0;
    String info[] = new String[80];
    String respuestabien="";
    int p=0;
    int op1=1;
    int op2=2;
    int op3=3;
    int op4=4;
    int r=5;
    int puntos1=6;
    int n=0;
    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        empezar = new javax.swing.JButton();
        Preguntas = new javax.swing.JLabel();
        Respuestas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargar.setText("Cargar examen");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        jPanel1.add(cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 400, -1));

        siguiente.setText("Siguiente pregunta");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 400, -1));

        reiniciar.setText("Reiniciar examen");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 400, -1));

        empezar.setText("Empezar");
        empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarActionPerformed(evt);
            }
        });
        jPanel1.add(empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 400, -1));

        Preguntas.setText("                        Preguntas");
        jPanel1.add(Preguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 146, 247, -1));

        Respuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestasActionPerformed(evt);
            }
        });
        jPanel1.add(Respuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 168, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
         String linea="";
        File f = new File("examen.txt");
        try{
            FileReader leer = new FileReader("ExamenApp/src/examen.txt.rtf");
            BufferedReader bufferLeer = new BufferedReader(leer);

            while((linea=bufferLeer.readLine())!=null)
            {
                info[n] = linea;
                n = n + 1;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cargarActionPerformed

    private void empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarActionPerformed
        // TODO add your handling code here:
      cargar.setEnabled(false);
        empezar.setEnabled(false);
        
        Respuestas.removeAllItems();
        Preguntas.setText("");
        
        String pregunta[] = info[p].split(":p;");        
        Preguntas.setText(pregunta[1]);
        
        String respuesta[] = info[op1].split(":op1;");
        String respuesta2[] = info[op2].split(":op2;");
        String respuesta3[] = info[op3].split(":op3;");
        String respuesta4[] = info[op4].split(":op4;");
        String resBien[] = info[r].split(":r;");
        String puntos = info[puntos1];
        a = Integer.parseInt(puntos);
        respuestabien  = resBien[1];
        puntostotal = puntostotal + a;
        
        Respuestas.addItem(respuesta[1]);
        Respuestas.addItem(respuesta2[1]);
        Respuestas.addItem(respuesta3[1]);
        Respuestas.addItem(respuesta4[1]);
        Respuestas.setSelectedIndex(-1);
        
        p = p + 7;
        op1 = op1 + 7;
        op2 = op2 + 7;
        op3 = op3 + 7;
        op4 = op4 +7 ;
        r = r + 7;
    }//GEN-LAST:event_empezarActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        cargar.setEnabled(true);
        empezar.setEnabled(true);
        puntosExamen=0;
        puntostotal=0;
        a=0;
        p=0;
        op1=1;
        op2=2;
        op3=3;
        op4=4;
        r=5;
        puntos1=6;
        n = 0;
        Respuestas.removeAllItems();
        Preguntas.setText("");
    }//GEN-LAST:event_reiniciarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
         if(info[p]==null)
        {
            if(seleccion.equals(respuestabien))
            {
                puntosExamen = puntosExamen + a;
            }
            JOptionPane.showMessageDialog(null,puntosExamen+" de "+puntostotal);
            reiniciar.doClick();
        }
        else
        {
            
            if(seleccion.equals(respuestabien))
            {
                puntosExamen = puntosExamen + a;
            }
            
            Preguntas.setText("");

            String pregunta[] = info[p].split(":p;");

            Preguntas.setText(pregunta[1]);

            String respuesta[] = info[op1].split(":op1;");
            String respuesta2[] = info[op2].split(":op2;");
            String respuesta3[] = info[op3].split(":op3;");
            String respuesta4[] = info[op4].split(":op4;");
            String resBien[] = info[r].split(":r;");
            String puntos = info[puntos1];
            Respuestas.removeAllItems();
            a = Integer.parseInt(puntos);
            respuestabien  = resBien[1];
            puntostotal = puntostotal + a;
            
            Respuestas.addItem(respuesta[1]);
            Respuestas.addItem(respuesta2[1]);
            Respuestas.addItem(respuesta3[1]);
            Respuestas.addItem(respuesta4[1]);
            Respuestas.setSelectedIndex(-1);

            p = p + 7;
            op1 = op1 + 7;
            op2 = op2 + 7;
            op3 = op3 + 7;
            op4 = op4 +7 ;
            r = r + 7;
            puntos1 = puntos1 + 7;
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void RespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestasActionPerformed
        // TODO add your handling code here:
         if(Respuestas.getSelectedIndex()!=-1)
        {
            seleccion = Respuestas.getSelectedItem().toString();
        }
    }//GEN-LAST:event_RespuestasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Preguntas;
    private javax.swing.JComboBox<String> Respuestas;
    private javax.swing.JButton cargar;
    private javax.swing.JButton empezar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
